name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      # - name: System Deps
      #   run: |
      #     sudo apt update
      #     sudo apt install libgirepository1.0-dev libgtk-3-dev libadwaita-1-dev
      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}
      - name: Install Dependencies
        run: poetry install --no-interaction --no-root
        if: steps.cache-deps.outputs.cache-hit != 'true'
      - name: Install Project
        run: poetry install --no-interaction
      - name: Check code formatting
        run: poetry run black --check ibroadcastdl
      - name: Lint code
        run: poetry run ruff ibroadcastdl
      # - name: Run pytest
      #   run: poetry run pytest --cov=ibroadcastdl --cov-report=term-missing
